# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2


    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        sudo apt update -yq
        sudo apt install -yq --no-install-recommends python3-setuptools python3-pip g++ gfortran gobjc gobjc++ zlib1g-dev python-dev python3-dev python3-jsonschema
        sudo apt-get install python3.6
        sudo pip install ninja
        sudo pip3 install meson
        sudo apt-get install gtk-doc-tools
        sudo apt-get install -y xsltproc
        sudo apt-get install libxml2-utils
    - name: Python version
      run: python3 --version
    - name: Meson version
      run: meson --version
    - name: Ninja version
      run: ninja --version
    - name: Build source code
      run: |
        meson builddir
        ninja -C builddir
        ninja -C builddir check-xml
